### ISSUE TITLE
[feature]: Add model sampling settings

### ISSUE THREAD

**Issue by cbh778899** [SkywardAI/skywardai.io#47]
- [ ] **Context Length**: `n_ctx`
- [ ] **Batch Size**: `n_batch`
- [ ] **N Predict**: `nPredict`
- [ ] **Temperature**: `temp`

**Comment by Aisuko** [comment]
@cbh778899 Is there any reference can help fix this issue?. I believe it is a good start point for @Murkeee to familiar hyper parameter settings of language model.

**Comment by cbh778899** [comment]
[This line](https://github.com/ngxson/wllama/blob/7beefeb9a4552f8f346efb50e2d1e6546bdaaa33/examples/main/src/utils/wllama.context.tsx#L171) and [this line](https://github.com/ngxson/wllama/blob/7beefeb9a4552f8f346efb50e2d1e6546bdaaa33/examples/main/src/utils/wllama.context.tsx#L207) both have references, those are different parts, some are part of [model config](https://github.ngxson.com/wllama/docs/interfaces/LoadModelConfig.html) should be specified when load model, and others are part of [sampling](https://github.ngxson.com/wllama/docs/interfaces/SamplingConfig.html) that should be specified when doing completions.  
  
Please read the sourcecode of their [example application](https://github.com/ngxson/wllama/tree/master/examples/main) for more information.  
  
The settings can be functions that can be called by page components, however page components are not developed yet, if anyone interested in page design they are also welcome to contribute on this part.

**Comment by Murkeee** [comment]
👍 Will work on this.
