### ISSUE TITLE
Improve the basic framework of the document

### ISSUE THREAD

**Issue by arvin936** [SkywardAI/skywardai.io#5]
### Improve the basic framework of the document - Tutorial

In this part, we will run through a simple, practical, and complete process to tell users how to run a practical case, which roughly includes preparation, front-end and back-end configuration, packaging/publishing, and running...

### Improve the basic framework of the document - Processes

In this part, we need to introduce to users what components our project contains, the relationships between the components, and the logic of the project running using these components. May include etcd, PostgreSQL, etc.

### Improve the basic framework of the document - Examples

In this part, we need to show users how to use the core functions of our project to achieve small and classic requirements. The goal is to demonstrate the core functions through small cases.

### Improve the basic framework of the document - Contributing

In this part, we need to tell users how to contribute to our open source project, such as coding style, pull request format, and basic etiquette requirements for participating in discussions.

### Improve the basic framework of the document - FAQ

In this part, we need to list some common questions for newcomers to the project or users who are interested in the project, such as project goals, operating platform adaptation, usage scenarios, version update frequency, etc.

We can refer to the following cases:
https://www.electronjs.org/docs/latest/

**Comment by Aisuko** [comment]
https://github.com/SkywardAI/skywardai.io/commit/3a1c3069da9e87f18ec762590c03c60c67aff17e

**Comment by Aisuko** [comment]
Close by 76e7a03457d7187b266f7cee2f75f34e3466f9de
